# Generated by Django 5.0.2 on 2024-03-07 13:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("django_telethon", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewDialogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "have_to_start",
                    models.BooleanField(
                        default=True, verbose_name="Have to start dialog"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Phone number",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "client_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_telethon.clientsession",
                        verbose_name="Client session",
                    ),
                ),
            ],
            options={
                "verbose_name": "New Dialog",
                "verbose_name_plural": "New Dialogs",
            },
        ),
    ]
